apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana
spec:
  secretName: kibana-cert
  privateKey:
    rotationPolicy: Always
  dnsNames:
  - kibana.localdomain
  issuerRef:
    name: lab-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
