apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.15.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  config:
    server.publicBaseUrl: https://kibana.localdomain
  http:
    service:
      metadata:
        annotations:
          traefik.ingress.kubernetes.io/service.serversscheme: http
    tls:
      selfSignedCertificate:
        disabled: true
